//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GJIService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName= "GJIService.IUrbanAppealService")]
    public interface IUrbanAppealService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/CreateUrbanAppeal", ReplyAction="http://tempuri.org/IUrbanAppealService/CreateUrbanAppealResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CreateUrbanAppealAsync(GJIService.CreateUrbanAppealRequest urbanAppeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetListUrbanAppeal", ReplyAction="http://tempuri.org/IUrbanAppealService/GetListUrbanAppealResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.UrbanAppealListResponse[]> GetListUrbanAppealAsync(long CorrespondentId, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetOpenList", ReplyAction="http://tempuri.org/IUrbanAppealService/GetOpenListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.OpenListResponse[]> GetOpenListAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetUrbanAppeal", ReplyAction="http://tempuri.org/IUrbanAppealService/GetUrbanAppealResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.UrbanAppealResponse> GetUrbanAppealAsync(long AppealId, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetFile", ReplyAction="http://tempuri.org/IUrbanAppealService/GetFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.GetFileResponse> GetFileAsync(long FileId, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetUserRequestsResponce", ReplyAction="http://tempuri.org/IUrbanAppealService/GetUserRequestsResponceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.GetUserRequestsResponce> GetUserRequestsResponceAsync(string esiaid, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/CreateExamRequest", ReplyAction="http://tempuri.org/IUrbanAppealService/CreateExamRequestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.RequestToExamResponce> CreateExamRequestAsync(GJIService.PersonExamRequest PersonExamRequest, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetListOnlineSurvey", ReplyAction="http://tempuri.org/IUrbanAppealService/GetListOnlineSurveyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.ListOnlineSurveyResponce> GetListOnlineSurveyAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/GetRealityList", ReplyAction="http://tempuri.org/IUrbanAppealService/GetRealityListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.RealityListResponce> GetRealityListAsync(GJIService.RealityListRequest RealityListRequest, string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUrbanAppealService/CreateSurveyResult", ReplyAction="http://tempuri.org/IUrbanAppealService/CreateSurveyResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<GJIService.RequestResult> CreateSurveyResultAsync(GJIService.OnlineSurveyProxy OnlineSurveyProxy, string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUrbanAppealRequest
    {
        
        private long correspondentIdField;
        
        private string tokenField;
        
        private string appealDateField;
        
        private long realityObjectField;
        
        private string correspondentField;
        
        private string phoneNumberField;
        
        private string appealTextField;
        
        private string filePathField;
        
        private string fileNameField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CorrespondentId
        {
            get
            {
                return this.correspondentIdField;
            }
            set
            {
                this.correspondentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AppealDate
        {
            get
            {
                return this.appealDateField;
            }
            set
            {
                this.appealDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long RealityObject
        {
            get
            {
                return this.realityObjectField;
            }
            set
            {
                this.realityObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Correspondent
        {
            get
            {
                return this.correspondentField;
            }
            set
            {
                this.correspondentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AppealText
        {
            get
            {
                return this.appealTextField;
            }
            set
            {
                this.appealTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FilePath
        {
            get
            {
                return this.filePathField;
            }
            set
            {
                this.filePathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RealityAddres
    {
        
        private string idField;
        
        private string addresField;
        
        private string ukField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Addres
        {
            get
            {
                return this.addresField;
            }
            set
            {
                this.addresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UK
        {
            get
            {
                return this.ukField;
            }
            set
            {
                this.ukField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RealityListResponce
    {
        
        private RealityAddres[] realityAddresesField;
        
        private RequestResult requestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public RealityAddres[] RealityAddreses
        {
            get
            {
                return this.realityAddresesField;
            }
            set
            {
                this.realityAddresesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestResult RequestResult
        {
            get
            {
                return this.requestResultField;
            }
            set
            {
                this.requestResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestResult
    {
        
        private string codeField;
        
        private string nameField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RealityListRequest
    {
        
        private string placeNameField;
        
        private string streetNameField;
        
        private string houseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PlaceName
        {
            get
            {
                return this.placeNameField;
            }
            set
            {
                this.placeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StreetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string House
        {
            get
            {
                return this.houseField;
            }
            set
            {
                this.houseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OnlineSurveyQuestionAnswerProxy
    {
        
        private string idField;
        
        private string answerField;
        
        private string isCorrectField;
        
        private string pointValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IsCorrect
        {
            get
            {
                return this.isCorrectField;
            }
            set
            {
                this.isCorrectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PointValue
        {
            get
            {
                return this.pointValueField;
            }
            set
            {
                this.pointValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OnlineSurveyQuestionProxy
    {
        
        private string idField;
        
        private string answerIdField;
        
        private string questionField;
        
        private bool isPoolField;
        
        private bool isFIOField;
        
        private bool isAddressField;
        
        private bool isActualField;
        
        private OnlineSurveyQuestionAnswerProxy[] answersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AnswerId
        {
            get
            {
                return this.answerIdField;
            }
            set
            {
                this.answerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Question
        {
            get
            {
                return this.questionField;
            }
            set
            {
                this.questionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsPool
        {
            get
            {
                return this.isPoolField;
            }
            set
            {
                this.isPoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsFIO
        {
            get
            {
                return this.isFIOField;
            }
            set
            {
                this.isFIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsAddress
        {
            get
            {
                return this.isAddressField;
            }
            set
            {
                this.isAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsActual
        {
            get
            {
                return this.isActualField;
            }
            set
            {
                this.isActualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public OnlineSurveyQuestionAnswerProxy[] Answers
        {
            get
            {
                return this.answersField;
            }
            set
            {
                this.answersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OnlineSurveyProxy
    {
        
        private string idField;
        
        private string nameField;
        
        private string introTextField;
        
        private string outtroTextField;
        
        private string fIOField;
        
        private string userIdField;
        
        private string phoneField;
        
        private string userNameField;
        
        private OnlineSurveyQuestionProxy[] questionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IntroText
        {
            get
            {
                return this.introTextField;
            }
            set
            {
                this.introTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OuttroText
        {
            get
            {
                return this.outtroTextField;
            }
            set
            {
                this.outtroTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FIO
        {
            get
            {
                return this.fIOField;
            }
            set
            {
                this.fIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public OnlineSurveyQuestionProxy[] Questions
        {
            get
            {
                return this.questionsField;
            }
            set
            {
                this.questionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListOnlineSurveyResponce
    {
        
        private OnlineSurveyProxy[] onlineSurveysField;
        
        private RequestResult requestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public OnlineSurveyProxy[] OnlineSurveys
        {
            get
            {
                return this.onlineSurveysField;
            }
            set
            {
                this.onlineSurveysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestResult RequestResult
        {
            get
            {
                return this.requestResultField;
            }
            set
            {
                this.requestResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestToExamResponce
    {
        
        private RequestToExamData requestToExamDataField;
        
        private RequestResult requestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestToExamData RequestToExamData
        {
            get
            {
                return this.requestToExamDataField;
            }
            set
            {
                this.requestToExamDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestResult RequestResult
        {
            get
            {
                return this.requestResultField;
            }
            set
            {
                this.requestResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RequestToExamData
    {
        
        private string requestNumField;
        
        private string requestDateField;
        
        private string examDateField;
        
        private string examTimeField;
        
        private string stateField;
        
        private string protocolNumField;
        
        private string protocolDateField;
        
        private string correctAnswersPercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RequestNum
        {
            get
            {
                return this.requestNumField;
            }
            set
            {
                this.requestNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestDate
        {
            get
            {
                return this.requestDateField;
            }
            set
            {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExamDate
        {
            get
            {
                return this.examDateField;
            }
            set
            {
                this.examDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExamTime
        {
            get
            {
                return this.examTimeField;
            }
            set
            {
                this.examTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProtocolNum
        {
            get
            {
                return this.protocolNumField;
            }
            set
            {
                this.protocolNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProtocolDate
        {
            get
            {
                return this.protocolDateField;
            }
            set
            {
                this.protocolDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CorrectAnswersPercent
        {
            get
            {
                return this.correctAnswersPercentField;
            }
            set
            {
                this.correctAnswersPercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class File
    {
        
        private string fileNameField;
        
        private string typeDocumentField;
        
        private string numberDocumentField;
        
        private string documentDateField;
        
        private string base64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TypeDocument
        {
            get
            {
                return this.typeDocumentField;
            }
            set
            {
                this.typeDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumberDocument
        {
            get
            {
                return this.numberDocumentField;
            }
            set
            {
                this.numberDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DocumentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Base64
        {
            get
            {
                return this.base64Field;
            }
            set
            {
                this.base64Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PortalPerson
    {
        
        private string nameField;
        
        private string surnameField;
        
        private string patronymicField;
        
        private string innField;
        
        private string emailField;
        
        private string phoneField;
        
        private string eSIAIDField;
        
        private string addressRegField;
        
        private string addressLiveField;
        
        private string addressBirthField;
        
        private string birthdateField;
        
        private string idNumberField;
        
        private string idSerialField;
        
        private string idIssuedByField;
        
        private string idIssuedDateField;
        
        private string personPlaceWorkNameField;
        
        private string personPlaceWorkOGRNField;
        
        private string personPlaceWorkINNField;
        
        private string workPositionField;
        
        private string dateStartWorkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Patronymic
        {
            get
            {
                return this.patronymicField;
            }
            set
            {
                this.patronymicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Inn
        {
            get
            {
                return this.innField;
            }
            set
            {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ESIAID
        {
            get
            {
                return this.eSIAIDField;
            }
            set
            {
                this.eSIAIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AddressReg
        {
            get
            {
                return this.addressRegField;
            }
            set
            {
                this.addressRegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AddressLive
        {
            get
            {
                return this.addressLiveField;
            }
            set
            {
                this.addressLiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AddressBirth
        {
            get
            {
                return this.addressBirthField;
            }
            set
            {
                this.addressBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Birthdate
        {
            get
            {
                return this.birthdateField;
            }
            set
            {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IdNumber
        {
            get
            {
                return this.idNumberField;
            }
            set
            {
                this.idNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string IdSerial
        {
            get
            {
                return this.idSerialField;
            }
            set
            {
                this.idSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string IdIssuedBy
        {
            get
            {
                return this.idIssuedByField;
            }
            set
            {
                this.idIssuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string IdIssuedDate
        {
            get
            {
                return this.idIssuedDateField;
            }
            set
            {
                this.idIssuedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PersonPlaceWorkName
        {
            get
            {
                return this.personPlaceWorkNameField;
            }
            set
            {
                this.personPlaceWorkNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string PersonPlaceWorkOGRN
        {
            get
            {
                return this.personPlaceWorkOGRNField;
            }
            set
            {
                this.personPlaceWorkOGRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PersonPlaceWorkINN
        {
            get
            {
                return this.personPlaceWorkINNField;
            }
            set
            {
                this.personPlaceWorkINNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WorkPosition
        {
            get
            {
                return this.workPositionField;
            }
            set
            {
                this.workPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string DateStartWork
        {
            get
            {
                return this.dateStartWorkField;
            }
            set
            {
                this.dateStartWorkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PersonExamRequest
    {
        
        private PortalPerson portalPersonField;
        
        private File[] filesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PortalPerson PortalPerson
        {
            get
            {
                return this.portalPersonField;
            }
            set
            {
                this.portalPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public File[] Files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestsResponce
    {
        
        private RequestToExamData[] requestToExamDataField;
        
        private RequestResult requestResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public RequestToExamData[] RequestToExamData
        {
            get
            {
                return this.requestToExamDataField;
            }
            set
            {
                this.requestToExamDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RequestResult RequestResult
        {
            get
            {
                return this.requestResultField;
            }
            set
            {
                this.requestResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileResponse
    {
        
        private string fileNameField;
        
        private string fileField;
        
        private string resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UrbanAppealResponse
    {
        
        private long correspondentIdField;
        
        private System.DateTime appealDateField;
        
        private System.Nullable<System.DateTime> executeDateField;
        
        private string correspondentField;
        
        private string phoneNumberField;
        
        private string appealTextField;
        
        private long appealFileField;
        
        private string appealFileNameField;
        
        private long answerFileField;
        
        private string answerFileNameField;
        
        private string appealStateField;
        
        private string answerTextField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long CorrespondentId
        {
            get
            {
                return this.correspondentIdField;
            }
            set
            {
                this.correspondentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AppealDate
        {
            get
            {
                return this.appealDateField;
            }
            set
            {
                this.appealDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> ExecuteDate
        {
            get
            {
                return this.executeDateField;
            }
            set
            {
                this.executeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Correspondent
        {
            get
            {
                return this.correspondentField;
            }
            set
            {
                this.correspondentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AppealText
        {
            get
            {
                return this.appealTextField;
            }
            set
            {
                this.appealTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long AppealFile
        {
            get
            {
                return this.appealFileField;
            }
            set
            {
                this.appealFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AppealFileName
        {
            get
            {
                return this.appealFileNameField;
            }
            set
            {
                this.appealFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long AnswerFile
        {
            get
            {
                return this.answerFileField;
            }
            set
            {
                this.answerFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AnswerFileName
        {
            get
            {
                return this.answerFileNameField;
            }
            set
            {
                this.answerFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AppealState
        {
            get
            {
                return this.appealStateField;
            }
            set
            {
                this.appealStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string AnswerText
        {
            get
            {
                return this.answerTextField;
            }
            set
            {
                this.answerTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenListResponse
    {
        
        private System.DateTime appealDateField;
        
        private string appealTextField;
        
        private string answerTextField;
        
        private string addressField;
        
        private string appealStateField;
        
        private long appealFileField;
        
        private string appealFileNameField;
        
        private long answerFileField;
        
        private string answerFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime AppealDate
        {
            get
            {
                return this.appealDateField;
            }
            set
            {
                this.appealDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AppealText
        {
            get
            {
                return this.appealTextField;
            }
            set
            {
                this.appealTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnswerText
        {
            get
            {
                return this.answerTextField;
            }
            set
            {
                this.answerTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AppealState
        {
            get
            {
                return this.appealStateField;
            }
            set
            {
                this.appealStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long AppealFile
        {
            get
            {
                return this.appealFileField;
            }
            set
            {
                this.appealFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AppealFileName
        {
            get
            {
                return this.appealFileNameField;
            }
            set
            {
                this.appealFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long AnswerFile
        {
            get
            {
                return this.answerFileField;
            }
            set
            {
                this.answerFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AnswerFileName
        {
            get
            {
                return this.answerFileNameField;
            }
            set
            {
                this.answerFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UrbanAppealListResponse
    {
        
        private long appealIdField;
        
        private System.DateTime appealDateField;
        
        private string appealNumberField;
        
        private string appealStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long AppealId
        {
            get
            {
                return this.appealIdField;
            }
            set
            {
                this.appealIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime AppealDate
        {
            get
            {
                return this.appealDateField;
            }
            set
            {
                this.appealDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AppealNumber
        {
            get
            {
                return this.appealNumberField;
            }
            set
            {
                this.appealNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AppealState
        {
            get
            {
                return this.appealStateField;
            }
            set
            {
                this.appealStateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IUrbanAppealServiceChannel : GJIService.IUrbanAppealService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class UrbanAppealServiceClient : System.ServiceModel.ClientBase<GJIService.IUrbanAppealService>, GJIService.IUrbanAppealService
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UrbanAppealServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(UrbanAppealServiceClient.GetBindingForEndpoint(endpointConfiguration), UrbanAppealServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrbanAppealServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UrbanAppealServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrbanAppealServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UrbanAppealServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UrbanAppealServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> CreateUrbanAppealAsync(GJIService.CreateUrbanAppealRequest urbanAppeal)
        {
            return base.Channel.CreateUrbanAppealAsync(urbanAppeal);
        }
        
        public System.Threading.Tasks.Task<GJIService.UrbanAppealListResponse[]> GetListUrbanAppealAsync(long CorrespondentId, string Token)
        {
            return base.Channel.GetListUrbanAppealAsync(CorrespondentId, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.OpenListResponse[]> GetOpenListAsync(string Token)
        {
            return base.Channel.GetOpenListAsync(Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.UrbanAppealResponse> GetUrbanAppealAsync(long AppealId, string Token)
        {
            return base.Channel.GetUrbanAppealAsync(AppealId, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.GetFileResponse> GetFileAsync(long FileId, string Token)
        {
            return base.Channel.GetFileAsync(FileId, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.GetUserRequestsResponce> GetUserRequestsResponceAsync(string esiaid, string Token)
        {
            return base.Channel.GetUserRequestsResponceAsync(esiaid, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.RequestToExamResponce> CreateExamRequestAsync(GJIService.PersonExamRequest PersonExamRequest, string Token)
        {
            return base.Channel.CreateExamRequestAsync(PersonExamRequest, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.ListOnlineSurveyResponce> GetListOnlineSurveyAsync(string Token)
        {
            return base.Channel.GetListOnlineSurveyAsync(Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.RealityListResponce> GetRealityListAsync(GJIService.RealityListRequest RealityListRequest, string Token)
        {
            return base.Channel.GetRealityListAsync(RealityListRequest, Token);
        }
        
        public System.Threading.Tasks.Task<GJIService.RequestResult> CreateSurveyResultAsync(GJIService.OnlineSurveyProxy OnlineSurveyProxy, string Token)
        {
            return base.Channel.CreateSurveyResultAsync(OnlineSurveyProxy, Token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrbanAppealService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IUrbanAppealService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUrbanAppealService))
            {
                return new System.ServiceModel.EndpointAddress("http://www.adm-ezhkh.gzhi-samara.ru/EZHKH/WS/GJIService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IUrbanAppealService))
            {
                return new System.ServiceModel.EndpointAddress("https://www.adm-ezhkh.gzhi-samara.ru/EZHKH/WS/GJIService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUrbanAppealService,
            
            BasicHttpsBinding_IUrbanAppealService,
        }
    }
}
